from pydantic import BaseModel, Field


class Difference(BaseModel):
    """
    A data class to hold the details of a diff.

    Attributes:
        file (str): The file path of the changed file.
        change_type (str): The type of change (e.g., 'A' for added, 'M' for modified).
        diff (str): The diff details as a string.
    """
    file: str = Field(description="The file path of the changed file.")
    change_type: str | None = Field(description="The type of change (e.g., 'A' for added, 'M' for modified).", default=None)
    diff: str = Field(description="The diff details as a string.")
    comment: str | None = Field(description="The comment for the diff. Generated by the LLM Reviewer", default=None)
